name: Mirror Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Push to mirror
        run: |
          git config --global user.nama 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote add mirror https://$GITHUB_ACTOR:${{ secrets.TOKEN }}@github.com/JeiHyde25/JeiHyde25.git
          git push --mirror mirror