name: Mirror to JeiHyde25

on:
  push:
    branches:
      - main  # Update if your branch name differs

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Mirror push to JeiHyde25 repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add mirror https://x-access-token:${{ secrets.TOKEN }}@github.com/JeiHyde25/JeiHyde25.git
          git remote -v
          git config --get remote.mirror.url
          echo "Token begins with: ${TOKEN:0:4}"
          git push --mirror mirror
        env:
          TOKEN: ${{ secrets.TOKEN }}